### ISSUE TITLE
Data concatenation

### ISSUE THREAD

**Issue by Pawloch247** [jakubkala/ncn-grants#2]
Append ncn_2019 to grants_larger
Merge it with ncn_fill by id
Remove data which doesn't concern panels held in 2020, link below
https://ncn.gov.pl/finansowanie-nauki/konkursy/harmonogram

**Comment by jakubkala** [comment]
> Remove data which doesn't concern panels held in 2020, link below
https://ncn.gov.pl/finansowanie-nauki/konkursy/harmonogram

?

**Comment by Pawloch247** [comment]
np uwertura nie odbywa się w 2020 dlatego nie potrzebujemy danych dotyczących uwertury
